service: new-product-request-processor

plugins:
  - serverless-offline
  - serverless-pseudo-parameters

custom:
  topic: NEW_PROD_REQ
  stage: ${opt:stage, self:provider.stage}
  config: ${file(env-${self:custom.stage}.yml)}
  env:
    dev:
      ACCOUNT_ID: ${self:custom.config.ACCOUNT_ID}
      REGION: us-east-2
    prod:
      ACCOUNT_ID: '#{AWS::AccountId}'
      REGION: '#{AWS:Region}'

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-2
  stage: dev
  environment:
    REGION: ${self:custom.env.${self:custom.stage}.REGION}
    TOPIC_ARN: 'arn:aws:sns:${self:provider.region}:${self:custom.env.${self:custom.stage}.ACCOUNT_ID}:${self:custom.topic}'
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

functions:
  addNote:
    handler: addNote.addNote
    events:
      - http:
          path: notes
          method: post
          cors: true

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.topic}-QUEUE

    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: SNS Topic
        TopicName: ${self:custom.topic}
        Subscription:
          - Endpoint:
              Fn::GetAtt:
                - SQSQueue
                - Arn
            Protocol: sqs

    SQSQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Id: SQSQueuePolicy
          Statement:
          - Sid: Allow-SendMessage-To-Both-Queues-From-SNS-Topic
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
            - sqs:SendMessage
            Resource: "*"
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: SNSTopic
        Queues:
        - Ref: SQSQueue

    # SNSSubscription:
    #   Type: AWS::SNS::Subscription
    #   Properties:
    #       Endpoint: arn:aws:sqs:us-east-2:616874792320:${self:custom.topic}-QUEUE
    #       Protocol: sqs
    #       TopicArn: arn:aws:sns:us-east-2:616874792320:${self:custom.topic}
            # { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.topic}" ] ]  }


