service: new-product-request-processor

plugins:
  - serverless-offline
  - serverless-pseudo-parameters

custom:
  topic: NEW_PROD_REQ
  stage: ${opt:stage, self:provider.stage}
  config: ${file(env-${self:custom.stage}.yml)}
  env:
    dev:
      ACCOUNT_ID: ${self:custom.config.ACCOUNT_ID}
      REGION: us-east-2
    prod:
      ACCOUNT_ID: '#{AWS::AccountId}'
      REGION: '#{AWS:Region}'

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-2
  stage: dev
  environment:
    REGION: ${self:custom.env.${self:custom.stage}.REGION}
    TOPIC_ARN: 'arn:aws:sns:${self:provider.region}:${self:custom.env.${self:custom.stage}.ACCOUNT_ID}:${self:custom.topic}'
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

functions:
  addNote:
    handler: addNote.addNote
    events:
      - http:
          path: notes
          method: post
          cors: true

  analyzeNote:
    handler: analyzeNote.analyzeNote
    events:
      - sns: ${self:custom.topic}